# -*- coding: utf-8 -*-
"""LVADSUSR120.SnehaO-lab2.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1robiMRpDvKS9GuJ7KitE7S5PPBl-UaeW
"""

import pandas as pd
df = pd.read_csv("/content/booking.csv")
df.head()


duplicates = df[df.duplicated()]
print(duplicates)
df.drop_duplicates(inplace=True)


print(df.isnull().sum())


numerical_features = ['number of week nights', 'number of adults','number of children','number of weekend nights','number of week nights','lead time','average price']
for feature in numerical_features:
    lower_bound = df[feature].quantile(0.05)
    upper_bound = df[feature].quantile(0.95)
    df[feature] = df[feature].clip(lower=lower_bound, upper=upper_bound)

df.head()

from sklearn.preprocessing import LabelEncoder
label_encoder = LabelEncoder()


df["P-C"] = label_encoder.fit_transform(df["P-C"])
df["P-not-C"] = label_encoder.fit_transform(df["P-not-C"])
df["booking status"] = label_encoder.fit_transform(df["booking status"])
df["market segment type"] = label_encoder.fit_transform(df["market segment type"])
df["type of meal"] = label_encoder.fit_transform(df["type of meal"])
df["car parking space"] = label_encoder.fit_transform(df["car parking space"])
df["room type"] = label_encoder.fit_transform(df["room type"])
df["repeated"] = label_encoder.fit_transform(df["repeated"])

print(df.head())

import seaborn as sns
import matplotlib.pyplot as plt
correlation = df.corr()
sns.heatmap(correlation, annot=True, cmap='coolwarm')
plt.title('Correlation Chart')
plt.show()

from sklearn.tree import DecisionTreeClassifier

df = df.drop(['Booking_ID', 'date of reservation'], axis=1)

X = df.drop('booking status', axis=1)
y = df['booking status']

var_clas = DecisionTreeClassifier()
var_clas.fit(X, y)

feature_importance = dict(zip(X.columns, var_clas.feature_importances_))
print("Feature Importance:")
for feature, importance in sorted(feature_importance.items(), key=lambda x: x[1], reverse=True):
    print(f"{feature}: {importance:.4f}")

df = df.drop(['P-not-C', 'P-C', 'repeated'], axis=1)

from sklearn.model_selection import train_test_split
from sklearn.tree import DecisionTreeClassifier
from sklearn.metrics import accuracy_score, classification_report

X = df.drop('booking status', axis=1)
y = df['booking status']

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.3, random_state=42)

clas = DecisionTreeClassifier()

clas.fit(X_train, y_train)

y_pred = clas.predict(X_test)

accuracy = accuracy_score(y_test, y_pred)
print("Accuracy:", accuracy)

print("Classification Report:")
print(classification_report(y_test, y_pred))